import Fp.Basic
import Fp.Rounding
import Fp.MulInv
import Fp.Proofs.Grind
import Fp.ForLean.Rat

/-

template <class t>
  unpackedFloat<t> customRounder (const typename t::fpt &format,
				  const typename t::rm &roundingMode,
				  const unpackedFloat<t> &uf,
				  const customRounderInfo<t> &known) {

  typedef typename t::bwt bwt;
  typedef typename t::prop prop;
  typedef typename t::ubv ubv;
  typedef typename t::sbv sbv;


  //PRECONDITION(uf.valid(format));
  // Not a precondition because
  //  1. Exponent and significand may be extended.
  //  2. Their values may also be outside of the correct range.
  //
  // However this weaker condition will hold:
  sbv exp(uf.getExponent());
  bwt expWidth(exp.getWidth());
  PRECONDITION(uf.wellFormed(sbv::minValue(expWidth), sbv::maxValue(expWidth)));

  // Also there are some conditions on how the rounder is used.
  ubv psig(uf.getSignificand());
  bwt sigWidth(psig.getWidth());

  // unpack significand by adding the leading one.
  ubv sig(psig | unpackedFloat<t>::leadingOne(sigWidth));
  bwt targetSignificandWidth(unpackedFloat<t>::significandWidth(format));
  PRECONDITION(sigWidth >= targetSignificandWidth + 2); // need at least 2 more sig bits

  // * Must have at least enough exponent bits
  bwt targetExponentWidth(unpackedFloat<t>::exponentWidth(format));
  PRECONDITION(expWidth >= targetExponentWidth); // need at least as many exponent bits as target.

  // Also, do not round special values.
  // Note that this relies on these having default values and
  // the code that calls the rounder constructing uf from parts.
  //PRECONDITION(!uf.getNaN());
  //PRECONDITION(!uf.getInf());
  //PRECONDITION(!uf.getZero());  // Can be generated by the arithmetic part of add
  // The safe choice of default values means this should work OK


  // /*** Early underflow and overflow detection ***/
  bwt exponentExtension(expWidth - targetExponentWidth);
  prop earlyOverflow(exp > unpackedFloat<t>::maxNormalExponent(format).extend(exponentExtension));
  prop earlyUnderflow(exp < unpackedFloat<t>::minSubnormalExponent(format).extend(exponentExtension).decrement());
  // Optimisation : if the precondition on sigWidth and targetSignificandWidth is removed
  //                then can change to:
  //                   exponent >= minSubnormalExponent - 1
  //                && sigWidth > targetSignificandBits
  probabilityAnnotation<t>(earlyOverflow, UNLIKELY);  // (over,under)flows are generally rare events
  probabilityAnnotation<t>(earlyUnderflow, UNLIKELY);

  prop potentialLateOverflow(exp == unpackedFloat<t>::maxNormalExponent(format).extend(exponentExtension));
  prop potentialLateUnderflow(exp == unpackedFloat<t>::minSubnormalExponent(format).extend(exponentExtension).decrement());
  probabilityAnnotation<t>(potentialLateOverflow, VERYUNLIKELY);
  probabilityAnnotation<t>(potentialLateUnderflow, VERYUNLIKELY);



  /*** Normal or subnormal rounding? ***/
  prop normalRoundingRange(exp >= unpackedFloat<t>::minNormalExponent(format).extend(exponentExtension));
  probabilityAnnotation<t>(normalRoundingRange, LIKELY);
  prop normalRounding(normalRoundingRange || known.subnormalExact);



  /*** Round to correct significand. ***/
  // grab #bits from significand as needed for target.
  ubv extractedSignificand(sig.extract(sigWidth - 1, sigWidth - targetSignificandWidth).extend(1)); // extended to catch the overflow

  // Normal guard and sticky bits
  // grab guard and sticky bits
  bwt guardBitPosition(sigWidth - (targetSignificandWidth + 1));
  prop guardBit(sig.extract(guardBitPosition, guardBitPosition).isAllOnes());

  // stick: is the rest all zeroes?
  prop stickyBit(!sig.extract(guardBitPosition - 1,0).isAllZeros());


  // For subnormals, locating the guard and stick bits is a bit more involved
  //sbv subnormalAmount(uf.getSubnormalAmount(format)); // Catch is, uf isn't in the given format, so this doesn't work
  // minNormalExp - exp.  [how subnormal are we?]
  sbv subnormalAmount(expandingSubtract<t>(unpackedFloat<t>::minNormalExponent(format).matchWidth(exp),exp));
  // bollu: are INVARIANTs even compiled? >_< 'earlyUnderflow' is used below but commented out above.
  INVARIANT((subnormalAmount < sbv(expWidth + 1, sigWidth - 1)) || earlyUnderflow);
  // Note that this is negative if normal, giving a full subnormal mask
  // but the result will be ignored (see the next invariant)


  // Care is needed if the exponents are longer than the significands
  // In the case when data is lost it is negative and not used
  bwt extractedSignificandWidth(extractedSignificand.getWidth());
  // why does subnormal have a separate case?
  ubv subnormalShiftPrepared((extractedSignificandWidth >= expWidth + 1) ?
			     subnormalAmount.toUnsigned().matchWidth(extractedSignificand) :
			     subnormalAmount.toUnsigned().extract(extractedSignificandWidth - 1, 0));


  // Compute masks
  // what is this mask?: This masks converts a unary number to binary.
  // subnormalMask is a bitmask '000...111111', with as many '1's as subnormalShiftPrepared, which is how many exponents we are below min normal.
  ubv subnormalMask(orderEncode<t>(subnormalShiftPrepared)); // Invariant implies this if all ones, it will not be used
  ubv subnormalStickyMask(subnormalMask >> ubv::one(targetSignificandWidth + 1)); // +1 as the exponent is extended

  // Apply
  ubv subnormalMaskedSignificand(extractedSignificand & (~subnormalMask));
  ubv subnormalMaskRemoved(extractedSignificand & subnormalMask);
  // Optimisation : remove the masking with a single orderEncodeBitwise style construct

  prop subnormalGuardBit(!(subnormalMaskRemoved & (~subnormalStickyMask)).isAllZeros());
  prop subnormalStickyBit(guardBit || stickyBit ||
			  !((subnormalMaskRemoved & subnormalStickyMask).isAllZeros()));

  // (subnormalMask <<< 1) & ~ (subnormalMask) -> converts unary 'subnormalMask' to binary value.
  // But is this not just 'subnormalShiftPrepared'?
  // How is 'subnormalIncrementAmount' different from 'subnormalShiftPrepared'?
  ubv subnormalIncrementAmount((subnormalMask.modularLeftShift(ubv::one(targetSignificandWidth + 1))) & ~subnormalMask); // The only case when this looses info is earlyUnderflow
  INVARIANT(IMPLIES(subnormalIncrementAmount.isAllZeros(), earlyUnderflow || normalRounding));


  // Have to choose the right one dependent on rounding mode
  prop choosenGuardBit(ITE(normalRounding, guardBit, subnormalGuardBit));
  prop choosenStickyBit(ITE(normalRounding, stickyBit, subnormalStickyBit));

  prop significandEven(ITE(normalRounding,
			   extractedSignificand.extract(0,0).isAllZeros(),
			   ((extractedSignificand & subnormalIncrementAmount).isAllZeros())));
  // rounded up result.
  prop shouldRoundUp(roundingDecision<t>(roundingMode, uf.getSign(), significandEven,
				   choosenGuardBit, choosenStickyBit,
				   known.exact || (known.subnormalExact && !normalRoundingRange)));


  // Perform the increment as needed
  ubv leadingOne(unpackedFloat<t>::leadingOne(targetSignificandWidth)); // msb is 1, all other zeroes.
  // Not actually true, consider minSubnormalExponent - 1 : not an early underfow and empty significand
  //INVARIANT(!(subnormalMaskedSignificand & leadingOne).isAllZeros() ||
  //          earlyUnderflow); // This one really matters, it means only the early underflow path is wrong


  // -> +1 we need to increase the significand for rounding.
  ubv normalRoundUpAmount(ubv(shouldRoundUp).matchWidth(extractedSignificand));
  ubv subnormalRoundUpMask(ubv(shouldRoundUp).append(ubv::zero(targetSignificandWidth)).signExtendRightShift(ubv(targetSignificandWidth + 1, targetSignificandWidth)));
  // vvv subnormalRoundUpAmount := if shouldRoundUp then subnormalIncrementAmount else 0 vvv
  ubv subnormalRoundUpAmount(subnormalRoundUpMask & subnormalIncrementAmount);

  ubv rawRoundedSignificand((ITE(normalRounding,
				 extractedSignificand,
				 subnormalMaskedSignificand)
			     + // share adder :O
			     ITE(normalRounding,
				 normalRoundUpAmount,
				 subnormalRoundUpAmount)));

  // We might have lost the leading one, if so, re-add and note that we need to increment the significand
  prop significandOverflow(rawRoundedSignificand.extract(targetSignificandWidth, targetSignificandWidth).isAllOnes());
  INVARIANT(IMPLIES(significandOverflow, shouldRoundUp));

  ubv extractedRoundedSignificand(rawRoundedSignificand.extract(targetSignificandWidth - 1, 0));
  ubv roundedSignificand(extractedRoundedSignificand | leadingOne);
  INVARIANT(IMPLIES(significandOverflow, extractedRoundedSignificand.isAllZeros()));



  /*** Round to correct exponent. ***/

  // The extend is almost certainly unnecessary (see specialised rounders)
  sbv extendedExponent(exp.extend(1));

  prop incrementExponentNeeded(shouldRoundUp && significandOverflow);  // The roundUp is implied but kept for signal forwarding
  probabilityAnnotation<t>(incrementExponentNeeded, VERYUNLIKELY);
  prop incrementExponent(!known.noSignificandOverflow && incrementExponentNeeded);
  INVARIANT(IMPLIES(known.noSignificandOverflow, !incrementExponentNeeded));

  sbv correctedExponent(conditionalIncrement<t>(incrementExponent, extendedExponent));

  // Track overflows and underflows
  sbv maxNormal(unpackedFloat<t>::maxNormalExponent(format).matchWidth(correctedExponent));
  sbv minSubnormal(unpackedFloat<t>::minSubnormalExponent(format).matchWidth(correctedExponent));

  sbv correctedExponentInRange(collar<t>(correctedExponent, minSubnormal, maxNormal));


  // This can over and underflow but these values will not be used
  bwt currentExponentWidth(correctedExponentInRange.getWidth());
  sbv roundedExponent(correctedExponentInRange.contract(currentExponentWidth - targetExponentWidth));



  /*** Finish ***/

  prop computedOverflow(potentialLateOverflow && incrementExponentNeeded);
  prop computedUnderflow(potentialLateUnderflow && !incrementExponentNeeded);
  probabilityAnnotation<t>(computedOverflow, UNLIKELY);
  probabilityAnnotation<t>(computedUnderflow, UNLIKELY);

  prop lateOverflow(!earlyOverflow && computedOverflow);
  prop lateUnderflow(!earlyUnderflow && computedUnderflow);
  probabilityAnnotation<t>(lateOverflow, VERYUNLIKELY);
  probabilityAnnotation<t>(lateUnderflow, VERYUNLIKELY);


  // So that ITE abstraction works...
  prop overflow(!known.noOverflow && ITE(lateOverflow, prop(true), earlyOverflow));
  prop underflow(!known.noUnderflow && ITE(lateUnderflow, prop(true), earlyUnderflow));

  unpackedFloat<t> roundedResult(uf.getSign(), roundedExponent, roundedSignificand);
  // bollu: special cases.
  unpackedFloat<t> result(rounderSpecialCases<t>(format, roundingMode, roundedResult,
						 overflow, underflow, uf.getZero()));

  POSTCONDITION(result.valid(format));

  return result;
 }

 namespace symfpu {

  // The final reconstruction of the rounded result
  // Handles the overflow and underflow conditions
  template <class t>
  unpackedFloat<t> rounderSpecialCases (const typename t::fpt &format,
					const typename t::rm &roundingMode,
					const unpackedFloat<t> &roundedResult,
					const typename t::prop &overflow,
					const typename t::prop &underflow,
					const typename t::prop &isZero)
  {
    typedef typename t::prop prop;
    typedef typename t::ubv ubv;

    /*** Underflow and overflow ***/

    // On overflow either return inf or max
    prop returnInf(roundingMode == t::RNE() ||
		   roundingMode == t::RNA() ||
		   (roundingMode == t::RTP() && !roundedResult.getSign()) ||
		   (roundingMode == t::RTN() &&  roundedResult.getSign()));
    probabilityAnnotation<t>(returnInf, LIKELY);  // Inf is more likely than max in most application scenarios

    // On underflow either return 0 or minimum subnormal
    prop returnZero(roundingMode == t::RNE() ||
		    roundingMode == t::RNA() ||
		    roundingMode == t::RTZ() ||
		    (roundingMode == t::RTP() &&  roundedResult.getSign()) ||
		    (roundingMode == t::RTN() && !roundedResult.getSign()));
    probabilityAnnotation<t>(returnZero, LIKELY);   // 0 is more likely than min in most application scenarios



    /*** Reconstruct ***/
    unpackedFloat<t> inf(unpackedFloat<t>::makeInf(format, roundedResult.getSign()));
    unpackedFloat<t> max(roundedResult.getSign(), unpackedFloat<t>::maxNormalExponent(format), ubv::allOnes(unpackedFloat<t>::significandWidth(format)));
    unpackedFloat<t> min(roundedResult.getSign(), unpackedFloat<t>::minSubnormalExponent(format), unpackedFloat<t>::leadingOne(unpackedFloat<t>::significandWidth(format)));
    unpackedFloat<t> zero(unpackedFloat<t>::makeZero(format, roundedResult.getSign()));

    unpackedFloat<t> result(ITE(isZero,
				zero,
				ITE(underflow,
				    ITE(returnZero, zero, min),
				    ITE(overflow,
					ITE(returnInf, inf, max),
					roundedResult))));
    return result;
  }

  template <class t>
    typename t::prop roundingDecision (const typename t::rm &roundingMode,
				     const typename t::prop &sign,
				     const typename t::prop &significandEven,
				     const typename t::prop &guardBit,
				     const typename t::prop &stickyBit,
				     const typename t::prop &knownRoundDown) {
    typedef typename t::prop prop;

    prop roundUpRNE(roundingMode == t::RNE() && guardBit && (stickyBit || !significandEven));
    prop roundUpRNA(roundingMode == t::RNA() && guardBit);
    prop roundUpRTP(roundingMode == t::RTP() && !sign && (guardBit || stickyBit));
    prop roundUpRTN(roundingMode == t::RTN() &&  sign && (guardBit || stickyBit));
    prop roundUpRTZ(roundingMode == t::RTZ() && prop(false));
    prop roundUp(!knownRoundDown &&
		 (roundUpRNE || roundUpRNA || roundUpRTP || roundUpRTN || roundUpRTZ));

    return roundUp;
  }

-/

@[bv_normalize]
def roundingDecision (mode : RoundingMode) (sign : Bool) (lsb guard sticky : Bool) : Bool :=
  match mode with
  | .RNE => guard && (sticky || lsb)
  | .RNA => guard
  | .RTZ => false
  | .RTP => if sign then (guard || sticky) else false
  | .RTN => if sign then false else (guard || sticky)

@[bv_normalize]
def EUnpackedFloat.round {ei si : Nat} {e s : Nat} (inUf : EUnpackedFloat ei si) (mode : RoundingMode) :
  EUnpackedFloat (exponentWidth e s) (s + 1) :=
  let inUf := inUf.normalize
  match inUf.state with
  | .NaN => EUnpackedFloat.mkNaN
  | .Infinity => EUnpackedFloat.mkInfinity inUf.num.sign
  -- | .Zero => EUnpackedFloat.mkZero inUf.num.sign
  | .Number =>
    let u := inUf.num
    let ew := exponentWidth e s
    let sw := s + 1

    let expVal := u.ex.toInt
    let minExp := minNormalExp e

    let isSubnormal := expVal < minExp
    let targetExpVal := if isSubnormal then minExp else expVal

    let rightShiftInt : Int := (targetExpVal - expVal) + ((si : Int) - (sw : Int))

    let (shiftedSig, guard, sticky) : BitVec sw × Bool × Bool :=
      if rightShiftInt > 0 then
        let rs := rightShiftInt.toNat
        -- If rs >= si + 1, all bits shifted out.
            --   rs-1 at least si. Guard is 0. Sticky is any bit set.
        if rs >= si + 1 then
           (0#sw, false, u.sig != 0#si)
        else
            -- Extract value and guard/sticky
            -- guard is at index rs - 1
            let guard := u.sig.getLsbD (rs - 1)
            -- sticky is any bit in [0, rs-2]
            let sticky := if rs > 1 then (u.sig.extractLsb (rs - 2) 0) != 0 else false

            let val := u.sig >>> rs
            (val.setWidth sw, guard, sticky)
      else
        let ls := (-rightShiftInt).toNat
        let val := u.sig.zeroExtend (si + ls) <<< ls
        (val.setWidth sw, false, false)

    let lsb := shiftedSig.getLsbD 0
    let roundUp := roundingDecision mode u.sign lsb guard sticky

    let sigOverflow := shiftedSig == BitVec.allOnes sw && roundUp

    let (finalSig, finalExpVal) :=
      if sigOverflow then
        (BitVec.ofNat sw 1 <<< (sw - 1), targetExpVal + 1)
      else if roundUp then
        (shiftedSig + 1, targetExpVal)
      else
        (shiftedSig, targetExpVal)

    if finalExpVal > maxNormalExp e then
       EUnpackedFloat.mkInfinity u.sign
    else if finalSig == 0 then
       EUnpackedFloat.mkZero u.sign
    else
       let finalExp := BitVec.ofInt ew finalExpVal
       EUnpackedFloat.mkNumber {
         sign := u.sign
         ex := finalExp
         sig := finalSig
       }
