name: FpRealTheory (with Mathlib)

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  build:
    name: FpRealTheory (mathlib)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Build FpRealTheory with lean-action
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: fp-real-theory
          use-mathlib-cache: true
          use-github-cache: true
          build: true
          test: false
